#!/bin/bash

# ## Created By Aditya Shakya
# MENU="$(rofi -sep "|" -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 5 <<< "> Lock|> Logout|> Reboot|> Suspend|> Shutdown")"
#             case "$MENU" in
#                 *Lock) dbus-send --type=method_call --dest=org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock ;;
#                 *Logout) swaymsg exit;;
#                 *Reboot) systemctl reboot ;;
#                 *Suspend) systemctl suspend;;
#                 *Shutdown) systemctl -i poweroff
#             esac

MENU_STRING='Lock\nLogout\nReboot\nSuspend\nShutdown'
COMMAND=$(echo -e $MENU_STRING | wofi -i -d -p"Powermenu")
echo $COMMAND
case "$COMMAND" in
  *Lock) echo "locking";;
  *Logout) echo "loggingout";;
  *Reboot) echo "Rebooting";;
  *Suspend) echo "Suspending";;
  *Shutdown) echo "Shutdowning"
esac
